name: End‑to‑End Smoke Test

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
               chromium-browser xvfb

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install package (editable)
        run: |
          python -m pip install --upgrade pip
          pip install .  # pulls selenium + webdriver‑manager

      - name: Launch Selenium in headless Xvfb (sanity check)
        run: |
          xvfb-run -a python - <<'PY'
          from review import chrome_driver
          drv = chrome_driver()        # webdriver‑manager auto‑installs driver
          print("[OK] Selenium opened Chromium:", drv.capabilities["browserVersion"])
          drv.quit()
          PY

      - name: Run unit tests
        run: |
          pip install pytest coverage
          coverage run -m pytest -q
          coverage report -m
